Update Linux install script to add support for the ARM build

diff --git a/script/install b/script/install
--- a/script/install
+++ b/script/install
@@ -2,7 +2,7 @@
 
 ######################################################################
 #
-# Site.js v12.7.1 Installer for Linux and macOS.
+# Site.js v12.7.1 Installer for Linux (x86 and armv7l) and macOS.
 #
 # To use:
 #
@@ -30,8 +30,18 @@ mkdir -p /tmp/sitejs.org
 pushd /tmp/sitejs.org > /dev/null
 
 if [[ "$OSTYPE" == "linux-gnu" ]]; then
-  # Linux
-  wget -q https://sitejs.org/releases/linux/12.7.1.tar.gz
+  cpuArchicture=`uname -m`
+  if [[ "$cpuArchitecture" == "x86_64" ]]; then
+    # Linux on x64
+    wget -q https://sitejs.org/releases/linux/12.7.1.tar.gz
+  elif [[ "$cpuArchitecture" == "armv7l" ]]; then
+    wget -q https://sitejs.org/releases/linux-arm/12.7.1.tar.gz
+  else
+    # Unsupported
+    echo "\n ❌ Error: this architecture is not supported on Linux (only x86_64 and armv7l are).\n"
+    cleanUp
+    exit 1
+  fi
 elif [[ "$OSTYPE" == "darwin"* ]]; then
   # macOS
   curl -Os https://sitejs.org/releases/macos/12.7.1.tar.gz
